### PR TITLE
riscv: add hardware benchmark support

### PR DESCRIPTION
**Pull request by niwis**
This adds support for the hardware benchmark application on RISC-V.

### CODE REVIEW

**Comment by kent-mcleod** [comment]
@ssrg-bamboo `test`

**Comment by ssrg-bamboo** [comment]
Hello, I'm a bot! I'll bring this PR into Trustworthy Systems and run some tests

**Comment by ssrg-bamboo** [comment]
## Test results for commit 50b7f9035e6372e32073ba70ba6a35317dabf3b6

### Summary

| Test name | Result |
| --- | --- |
| Code Quality - Check licenses - sel4bench - EXT-niwis-riscv-hardware-4 | SUCCESSFUL |
| Code Quality - Style - sel4bench - EXT-niwis-riscv-hardware-4 | FAILED |

### Detailed failure logs

| Project | Stage | Result summary |
| --- | --- | --- |
| Code Quality - Style - sel4bench - EXT-niwis-riscv-hardware-4 | Style check on changed files | 1 of 3 jobs failed |

**Job: gitlint**
Build logs

    17-Apr-2020 17:45:47	Build Code Quality - Style - sel4bench - EXT-niwis-riscv-hardware-4 - gitlint #1 (CQ-SEL4BENCHSTYLE37-SEL4BENCHGITLINTPR-1) started building on agent A local agent 1
    17-Apr-2020 17:45:47	I run on the Bamboo server!
    17-Apr-2020 17:45:47	Build working directory is /var/atlassian/application-data/bamboo/xml-data/build-dir/140083221/CQ-SEL4BENCHSTYLE37-SEL4BENCHGITLINTPR
    17-Apr-2020 17:45:47	Executing build Code Quality - Style - sel4bench - EXT-niwis-riscv-hardware-4 - gitlint #1 (CQ-SEL4BENCHSTYLE37-SEL4BENCHGITLINTPR-1)
    17-Apr-2020 17:45:47	Preparing artifact 'code' for use at /var/atlassian/application-data/bamboo/xml-data/build-dir/140083221/CQ-SEL4BENCHSTYLE37-SEL4BENCHGITLINTPR/. (location: .)
    17-Apr-2020 17:45:47	Artifact 'code' prepared in 35.37 ms at /var/atlassian/application-data/bamboo/xml-data/build-dir/140083221/CQ-SEL4BENCHSTYLE37-SEL4BENCHGITLINTPR/./code.tar.gz
    17-Apr-2020 17:45:47	Running pre-build action: VCS Version Collector
    17-Apr-2020 17:45:47	Starting task 'Untar code' of type 'com.atlassian.bamboo.plugins.scripttask:task.builder.script'
    17-Apr-2020 17:45:47	+ tar xf code.tar.gz --recursive-unlink
    17-Apr-2020 17:45:47	Finished task 'Untar code' with result: Success
    17-Apr-2020 17:45:47	Starting task 'Set permissions so Bamboo can cleanup' of type 'com.atlassian.bamboo.plugins.scripttask:task.builder.script'
    17-Apr-2020 17:45:47	+ chmod -R o+rwx /var/atlassian/application-data/bamboo/xml-data/build-dir/140083221/CQ-SEL4BENCHSTYLE37-SEL4BENCHGITLINTPR
    17-Apr-2020 17:45:47	Finished task 'Set permissions so Bamboo can cleanup' with result: Success
    17-Apr-2020 17:45:47	Starting task 'Lint commit messages' of type 'com.atlassian.bamboo.plugins.scripttask:task.builder.script'
    17-Apr-2020 17:45:47	+ cd sel4bench
    17-Apr-2020 17:45:47	+ gitlint --commits a9c64baa1018b4d771a93f5a708ef15e804b6d44..50b7f9035e6372e32073ba70ba6a35317dabf3b6 --config /var/atlassian/application-data/bamboo/xml-data/build-dir/140083221/CQ-SEL4BENCHSTYLE37-SEL4BENCHGITLINTPR/seL4_tools/misc/.gitlint
    17-Apr-2020 17:45:51	3: B6 Body message is missing
    17-Apr-2020 17:45:51	Failing task since return code of [/var/atlassian/application-data/bamboo/temp/CQ-SEL4BENCHSTYLE37-SEL4BENCHGITLINTPR-1-ScriptBuildTask-2522699584621031154.sh] was 1 while expected 0
    17-Apr-2020 17:45:51	Finished task 'Lint commit messages' with result: Failed
    17-Apr-2020 17:45:51	Starting task 'Set permissions so Bamboo can cleanup' of type 'com.atlassian.bamboo.plugins.scripttask:task.builder.script'
    17-Apr-2020 17:45:51	+ chmod -R o+rwx /var/atlassian/application-data/bamboo/xml-data/build-dir/140083221/CQ-SEL4BENCHSTYLE37-SEL4BENCHGITLINTPR
    17-Apr-2020 17:45:51	Finished task 'Set permissions so Bamboo can cleanup' with result: Success
    17-Apr-2020 17:45:51	Running post build plugin 'NCover Results Collector'
    17-Apr-2020 17:45:51	Running post build plugin 'Artifact Copier'
    17-Apr-2020 17:45:51	Running post build plugin 'npm Cache Cleanup'
    17-Apr-2020 17:45:51	Running post build plugin 'Clover Results Collector'
    17-Apr-2020 17:45:51	Running post build plugin 'Docker Container Cleanup'
    17-Apr-2020 17:45:51	Successfully removed working directory at '/var/atlassian/application-data/bamboo/xml-data/build-dir/140083221/CQ-SEL4BENCHSTYLE37-SEL4BENCHGITLINTPR'
    17-Apr-2020 17:45:51	Finalising the build...
    17-Apr-2020 17:45:51	Stopping timer.
    17-Apr-2020 17:45:51	Build CQ-SEL4BENCHSTYLE37-SEL4BENCHGITLINTPR-1 completed.
    17-Apr-2020 17:45:51	Running on server: post build plugin 'NCover Results Collector'
    17-Apr-2020 17:45:51	Running on server: post build plugin 'Build Hanging Detection Configuration'
    17-Apr-2020 17:45:51	Running on server: post build plugin 'Clover Delta Calculator'
    17-Apr-2020 17:45:51	Running on server: post build plugin 'Maven Dependencies Postprocessor'
    17-Apr-2020 17:45:52	All post build plugins have finished
    17-Apr-2020 17:45:52	Generating build results summary...
    17-Apr-2020 17:45:52	Saving build results to disk...
    17-Apr-2020 17:45:52	Store variable context...
    17-Apr-2020 17:45:52	Indexing build results...
    17-Apr-2020 17:45:52	Finished building CQ-SEL4BENCHSTYLE37-SEL4BENCHGITLINTPR-1.


This is the most I can report on right now, sorry!

**Comment by kent-mcleod** [comment]
Hi @niwis, thanks for the PR.  Are you able to add a commit message body and rebase the PR, then I'm happy to merge it.

**Comment by niwis** [comment]
Done

**Comment by niwis** [comment]
Okay, done.

**Comment by kent-mcleod** [comment]
Thanks!

@ssrg-bamboo `test`

**Comment by ssrg-bamboo** [comment]
Hello, I'm a bot! I'll bring this PR into Trustworthy Systems and run some tests

**Comment by ssrg-bamboo** [comment]
All the tests we ran have passed! Nice job!

**Pull request merged**
