### PR TITLE
Early Processing Methodology in More Benchmarks

### PR DESCRIPTION
**Pull request by Courtney3141**
Applies the early processing methodology in #26 to a larger selection of benchmarks:

- IRQ benchmarks: Without context switch, With context switch
- Scheduler benchmarks: Thread yield, Process yield
- Signal benchmarks: Signal to high prio thread
- Fault benchmarks: Fault round trip, faulter -> fault handler, fault handler -> faulter
- Hardware benchmarks: Hardware null_syscall thread
- Sync benchmarks: Producer to consumer, Consumer to producer

### CODE REVIEW

**Comment by lsf37** [comment]
The build failure is independent of this PR, I'll switch off QUARTZ64 for sel4bench CI for now (https://github.com/seL4/ci-actions/pull/245) so that we can see results here.

Does this PR supersede https://github.com/seL4/sel4bench/pull/26 or should it be merged afterwards?

**Comment by lsf37** [comment]
Ok, tests are in: we can ignore `hifive1` for now, because the board seems to have trouble atm, but `skylake` and `haswell3` both show failures for 32 bit runs with and without SMP for the `irq_user` benchmark, e.g. [here](https://github.com/seL4/sel4bench/actions/runs/3690023485/jobs/6248263626#step:5:166).

**Comment by Courtney3141** [comment]
The tests should be passing now, one of the problems was present in an old commit my work was based on, and rebasing to the latest master fixed the issue. The other problem was due to an assumption about the size of ccnt_t equaling word size, which is not true on ia32.

**Comment by lsf37** [comment]
Cool, thanks, these are now all passing.

**Review by lsf37 — APPROVED** [review]
From my side this looks good to merge.

Some of the early-processing results seem to have larger std-dev and variance than the late-processing method which is surprising to me after the discussion on the other PR, but I'd be fine to merge this first and improve things later.

**Comment by lsf37** [comment]
Some examples of higher std-dev in early processing on `SABRE_MCS_32`:

One-way IPC:

```json
        "Type": "With context switch",
        "Min": 813,
        "Max": 906,
        "Mean": 860.8800000000001,
        "Stddev": 19.02948270766213,
        "Variance": 358.49999999999994,
```

```json
        "Type": "With context switch (early processing)",
        "Min": 0,
        "Max": 0,
        "Mean": 864,
        "Stddev": 21.186521348930476,
        "Variance": 444.38,
```

```json
    "Benchmark": "Signal to high prio thread (early processing)",
    "Results": [
      {
        "Min": 0,
        "Max": 0,
        "Mean": 997,
        "Stddev": 119.62052795014202,
        "Variance": 14165.98,
[..]
  },
  {
    "Benchmark": "Signal to high prio thread",
    "Results": [
      {
        "Min": 900,
        "Max": 1116,
        "Mean": 1005.2199999999999,
        "Stddev": 43.50803942893193,
        "Variance": 1874.0200000000004,
```

For other benchmarks std-dev and variance are lower as expected, but not dramatically lower.

**Comment by gernotheiser** [comment]
Is this reproducible? i.e. do you get basically the same values on repeated runs?
Could be an issue on how things are coordinated, given there are two treads involved

**Comment by lsf37** [comment]
> Is this reproducible? i.e. do you get basically the same values on repeated runs?
> Could be an issue on how things are coordinated, given there are two treads involved

Will start another run

**Comment by lsf37** [comment]
For this run IPC is better than before, but still about the same as the late processing method:

```json
        "Type": "With context switch",
        "Min": 590,
        "Max": 661,
        "Mean": 634.1800000000001,
        "Stddev": 13.624102231565999,
        "Variance": 183.76000000000002,
```

```json
        "Type": "With context switch (early processing)",
        "Min": 0,
        "Max": 0,
        "Mean": 632,
        "Stddev": 13.31324243910642,
        "Variance": 175.47,
```

signal is still about the same:

```json
    "Benchmark": "Signal to high prio thread",
    "Results": [
      {
        "Min": 676,
        "Max": 835,
        "Mean": 754.3900000000001,
        "Stddev": 44.746310722028504,
        "Variance": 1982.2099999999996,
```

```json
    "Benchmark": "Signal to high prio thread (early processing)",
    "Results": [
      {
        "Min": 0,
        "Max": 0,
        "Mean": 755,
        "Stddev": 121.74970184353595,
        "Variance": 14674.76,
```

**Comment by lsf37** [comment]
As discussed separately with @gernotheiser, I'm proposing to merge this one even though there are still some benchmarks that show higher std dev in the early processing method, since this only adds new benchmarks and doesn't remove any old ones.

@kent-mcleod any concerns from your side before I do that?

**Pull request merged**
